// --- GAME MECHANICS ---
export const INITIAL_MAX_ENERGY = 1000;
export const ENERGY_REGEN_RATE = 2; // per second
export const SAVE_DEBOUNCE_MS = 3000;
export const REFERRAL_BONUS = 50000;
export const TELEGRAM_BOT_NAME = 'Ukhyliantbot';
export const MINI_APP_NAME = 'ukhyliant_game';
export const DEFAULT_COIN_SKIN_ID = 'default_coin';

// --- TRANSLATIONS ---
type TranslationKeys = {
  [key: string]: string;
};

type AllTranslations = {
  en: TranslationKeys;
  ua: TranslationKeys;
  ru: TranslationKeys;
};

export const TRANSLATIONS: AllTranslations = {
  en: {
    why_not_state_language: 'Why not in the state language?',
    skip_video: 'Skip',
    your_referrals: 'Your Referrals',
    referral_bonus: 'Referral Bonus',
    profit_from_referrals: 'Profit from Referrals',
    copied: 'Copied!',
    invite_friends: 'Invite Friends',
    skins_gallery_desc: 'Choose your disguise. Each skin gives a boost to passive income.',
    selected: 'Selected',
    select_skin: 'Select',
    black_market: 'Black Market',
    black_market_desc: 'Spend your resources to get rare cards and skins.',
    lootbox_coin: 'Coin Container',
    open_for: 'Open for',
    lootbox_star: 'Star Container',
    loading: 'Loading',
    market_purchase_success: 'Purchase successful!',
    market_no_listings: 'No items for sale right now.',
    market_invalid_price: 'Invalid price. Please enter a positive number.',
    market_list_success: 'Skin listed successfully!',
    market_set_price: 'Set Price',
    market_price_in_coins: 'Price in coins',
    market_list_for_sale: 'List for Sale',
    market_sell_desc: 'Select a skin you own to list it on the market.',
    market_no_skins_to_sell: 'You have no skins to sell.',
    market_buy: 'Buy',
    market_sell: 'Sell',
    underground_market: 'Underground Market',
    underground_market_desc: 'Trade skins with other players.',
    content_submission_error_url: 'Please enter a valid URL.',
    content_submission_success: 'Video submitted for review!',
    content_rewards_title: 'Content Creation Rewards',
    content_rewards_desc: 'Get rewarded for creating videos about the game!',
    content_reward_for_views: 'views',
    content_submit_title: 'Submit Your Video',
    content_submit_placeholder: 'https://youtube.com/watch?v=...',
    content_submit_button: 'Submit for Review',
    content_history_title: 'Your Submissions',
    content_no_submissions: 'You have not submitted any videos yet.',
    content_status_pending: 'Pending',
    content_status_approved: 'Approved',
    content_status_rejected: 'Rejected',
    profile: 'Dossier',
    sub_contacts: 'Contacts',
    sub_boosts: 'Boosts',
    sub_disguise: 'Disguise',
    sub_market: 'Market',
    sub_cell: 'Cell',
    sub_content: 'Content',
    completed: 'Completed',
    unlock_for: 'Unlock for',
    go_to_task: 'Go',
    claim: 'Claim',
    enter_secret_code: 'Enter Code',
    claim_reward: 'Claim Reward',
    market_wallet_connected: 'Wallet connected successfully',
    wallet_disconnected: 'Wallet disconnected',
    connect_your_ton_wallet: 'Connect TON Wallet',
    connect_wallet_task_desc: 'To participate in the airdrop, connect your TON wallet.',
    missions: 'Directives',
    sub_daily: 'Daily',
    sub_airdrop: 'Airdrop',
    airdrop_description: 'Complete special one-time tasks to earn big rewards for the future airdrop.',
    leaderboard: 'Leaderboard',
    your_league: 'Your League',
    total_players: 'Total Agents',
    won_item: 'You got an item',
    task_unlocked: 'Task Unlocked',
    profit_boost: 'profit boost',
    close: 'Close',
    glitch_codes_title: 'Glitch Codes',
    glitch_codes_desc: 'Enter discovered 4-character codes to claim rewards.',
    activate: 'Activate',
    claimed: 'Claimed',
    no_glitch_codes_found: 'No discovered codes yet.',
    penalty_title: 'Penalty',
    penalty_close: 'Understood',
    exchange: 'Stockpile',
    mine: 'Mine',
    boost_purchased: 'Boost purchased!',
    upgrade_purchased: 'Upgrade purchased!',
    task_completed: 'task completed',
    combo_collected: 'Combo collected!',
    cipher_solved: 'Cipher solved!',
    glitch_code_claimed: 'Glitch code claimed!',
    tooltip_energy: 'This is your Stamina. It is spent on taps and regenerates over time.',
    tooltip_suspicion: 'This is your Suspicion level. High-risk actions increase it. If it gets full, you will be penalized.',
    limit_reached: 'Limit reached',
    limit_today: 'Limit:',
    reset_limit_for: 'Reset for',
    lvl: 'Lvl',
    create_cell: 'Create Cell',
    enter_cell_name: 'Enter cell name',
    create: 'Create',
    join_cell: 'Join Cell',
    enter_invite_code: 'Enter invite code',
    join: 'Join',
    informant_dossier: 'Informant Dossier',
    recruit_informant: 'Recruit Informant',
    recruit_informant_desc: 'Recruit an AI-generated informant to boost your cell\'s profit.',
    recruiting: 'Recruiting...',
    recruit: 'Recruit',
    cell: 'Cell',
    no_cell_info: 'You are not part of a cell. Create one or join with an invite code.',
    total_cell_profit: 'Total Cell Profit',
    members: 'Members',
    cell_bank: 'Cell Bank',
    cell_tickets: 'Battle Tickets',
    invite_code: 'Invite Code',
    copy: 'Copy',
    buy_ticket: 'Buy Battle Ticket',
    leave_cell: 'Leave Cell',
    confirm_leave_cell: 'Are you sure you want to leave the cell?',
    cipher_hint: 'Enter Morse code for today\'s word',
    cancel_morse_mode: 'Cancel',
    daily_cipher: 'Daily Cipher',
    mine_upgrades: 'Upgrades',
    combo_not_active: 'Combo is not active today.',
    find_cards: 'Find and upgrade these cards today to get a big prize!',
    claimed_today: 'Claimed',
    check: 'Check',
    suspicion: 'Suspicion',
  },
  ua: {
    why_not_state_language: 'Чому не державною?',
    skip_video: 'Пропустити',
    your_referrals: 'Ваші реферали',
    referral_bonus: 'Бонус за реферала',
    profit_from_referrals: 'Прибуток від рефералів',
    copied: 'Скопійовано!',
    invite_friends: 'Запросити друзів',
    skins_gallery_desc: 'Виберіть своє маскування. Кожен скін дає бонус до пасивного доходу.',
    selected: 'Обрано',
    select_skin: 'Обрати',
    black_market: 'Чорний ринок',
    black_market_desc: 'Витрачайте свої ресурси, щоб отримати рідкісні карти та скіни.',
    lootbox_coin: 'Контейнер за монети',
    open_for: 'Відкрити за',
    lootbox_star: 'Зоряний контейнер',
    loading: 'Завантаження',
    market_purchase_success: 'Покупка успішна!',
    market_no_listings: 'Зараз немає товарів на продаж.',
    market_invalid_price: 'Невірна ціна. Будь ласка, введіть додатне число.',
    market_list_success: 'Скін успішно виставлено на продаж!',
    market_set_price: 'Встановити ціну',
    market_price_in_coins: 'Ціна в монетах',
    market_list_for_sale: 'Виставити на продаж',
    market_sell_desc: 'Виберіть скін, яким володієте, щоб виставити його на ринок.',
    market_no_skins_to_sell: 'У вас немає скінів для продажу.',
    market_buy: 'Купити',
    market_sell: 'Продати',
    underground_market: 'Підпільний ринок',
    underground_market_desc: 'Торгуйте скінами з іншими гравцями.',
    content_submission_error_url: 'Будь ласка, введіть дійсну URL-адресу.',
    content_submission_success: 'Відео надіслано на перевірку!',
    content_rewards_title: 'Нагороди за створення контенту',
    content_rewards_desc: 'Отримуйте нагороди за створення відео про гру!',
    content_reward_for_views: 'переглядів',
    content_submit_title: 'Надіслати своє відео',
    content_submit_placeholder: 'https://youtube.com/watch?v=...',
    content_submit_button: 'Надіслати на перевірку',
    content_history_title: 'Ваші заявки',
    content_no_submissions: 'Ви ще не надсилали жодного відео.',
    content_status_pending: 'Очікує',
    content_status_approved: 'Схвалено',
    content_status_rejected: 'Відхилено',
    profile: 'Досьє',
    sub_contacts: 'Контакти',
    sub_boosts: 'Посилення',
    sub_disguise: 'Маскування',
    sub_market: 'Ринок',
    sub_cell: 'Осередок',
    sub_content: 'Контент',
    completed: 'Виконано',
    unlock_for: 'Відкрити за',
    go_to_task: 'Перейти',
    claim: 'Забрати',
    enter_secret_code: 'Ввести код',
    claim_reward: 'Забрати нагороду',
    market_wallet_connected: 'Гаманець успішно підключено',
    wallet_disconnected: 'Гаманець відключено',
    connect_your_ton_wallet: 'Підключити TON гаманець',
    connect_wallet_task_desc: 'Для участі в аірдропі підключіть свій TON гаманець.',
    missions: 'Директиви',
    sub_daily: 'Щоденні',
    sub_airdrop: 'Airdrop',
    airdrop_description: 'Виконуйте спеціальні одноразові завдання, щоб заробити великі нагороди для майбутнього аірдропу.',
    leaderboard: 'Таблиця лідерів',
    your_league: 'Ваша ліга',
    total_players: 'Всього агентів',
    won_item: 'Ви отримали предмет',
    task_unlocked: 'Завдання розблоковано',
    profit_boost: 'до прибутку',
    close: 'Закрити',
    glitch_codes_title: 'Глітч-коди',
    glitch_codes_desc: 'Вводьте знайдені 4-значні коди, щоб отримати нагороди.',
    activate: 'Активувати',
    claimed: 'Отримано',
    no_glitch_codes_found: 'Ще не знайдено кодів.',
    penalty_title: 'Штраф',
    penalty_close: 'Зрозуміло',
    exchange: 'Схрон',
    mine: 'Майнінг',
    boost_purchased: 'Буст придбано!',
    upgrade_purchased: 'Покращення придбано!',
    task_completed: 'завдання виконано',
    combo_collected: 'Комбо зібрано!',
    cipher_solved: 'Шифр розгадано!',
    glitch_code_claimed: 'Глітч-код активовано!',
    tooltip_energy: 'Це ваша Витривалість. Вона витрачається на тапи та відновлюється з часом.',
    tooltip_suspicion: 'Це ваш рівень Підозри. Високоризикові дії підвищують його. Якщо він заповниться, вас оштрафують.',
    limit_reached: 'Ліміт досягнуто',
    limit_today: 'Ліміт:',
    reset_limit_for: 'Скинути за',
    lvl: 'Рів',
    create_cell: 'Створити осередок',
    enter_cell_name: 'Введіть назву осередку',
    create: 'Створити',
    join_cell: 'Приєднатись до осередку',
    enter_invite_code: 'Введіть код запрошення',
    join: 'Приєднатись',
    informant_dossier: 'Досьє інформатора',
    recruit_informant: 'Завербувати інформатора',
    recruit_informant_desc: 'Завербуйте згенерованого ШІ інформатора, щоб збільшити прибуток вашого осередку.',
    recruiting: 'Вербування...',
    recruit: 'Завербувати',
    cell: 'Осередок',
    no_cell_info: 'Ви не є частиною осередку. Створіть свій або приєднайтесь за кодом-запрошенням.',
    total_cell_profit: 'Загальний прибуток',
    members: 'Учасники',
    cell_bank: 'Банк осередку',
    cell_tickets: 'Квитки на битву',
    invite_code: 'Код запрошення',
    copy: 'Копіювати',
    buy_ticket: 'Купити квиток на битву',
    leave_cell: 'Покинути осередок',
    confirm_leave_cell: 'Ви впевнені, що хочете покинути осередок?',
    cipher_hint: 'Введіть код Морзе для сьогоднішнього слова',
    cancel_morse_mode: 'Скасувати',
    daily_cipher: 'Щоденний шифр',
    mine_upgrades: 'Покращення',
    combo_not_active: 'Комбо сьогодні неактивне.',
    find_cards: 'Знайдіть та прокачайте ці карти сьогодні, щоб отримати великий приз!',
    claimed_today: 'Отримано',
    check: 'Перевірити',
    suspicion: 'Підозра',
  },
  ru: {
    why_not_state_language: 'Почему не на государственном?',
    skip_video: 'Пропустить',
    your_referrals: 'Ваши рефералы',
    referral_bonus: 'Бонус за реферала',
    profit_from_referrals: 'Прибыль от рефералов',
    copied: 'Скопировано!',
    invite_friends: 'Пригласить друзей',
    skins_gallery_desc: 'Выберите свою маскировку. Каждый скин дает бонус к пассивному доходу.',
    selected: 'Выбрано',
    select_skin: 'Выбрать',
    black_market: 'Черный рынок',
    black_market_desc: 'Тратьте свои ресурсы, чтобы получить редкие карты и скины.',
    lootbox_coin: 'Контейнер за монеты',
    open_for: 'Открыть за',
    lootbox_star: 'Звездный контейнер',
    loading: 'Загрузка',
    market_purchase_success: 'Покупка успешна!',
    market_no_listings: 'Сейчас нет товаров на продажу.',
    market_invalid_price: 'Неверная цена. Пожалуйста, введите положительное число.',
    market_list_success: 'Скин успешно выставлен на продажу!',
    market_set_price: 'Установить цену',
    market_price_in_coins: 'Цена в монетах',
    market_list_for_sale: 'Выставить на продажу',
    market_sell_desc: 'Выберите скин, которым владеете, чтобы выставить его на рынок.',
    market_no_skins_to_sell: 'У вас нет скинов для продажи.',
    market_buy: 'Купить',
    market_sell: 'Продать',
    underground_market: 'Подпольный рынок',
    underground_market_desc: 'Торгуйте скинами с другими игроками.',
    content_submission_error_url: 'Пожалуйста, введите действительный URL-адрес.',
    content_submission_success: 'Видео отправлено на проверку!',
    content_rewards_title: 'Награды за создание контента',
    content_rewards_desc: 'Получайте награды за создание видео об игре!',
    content_reward_for_views: 'просмотров',
    content_submit_title: 'Отправить свое видео',
    content_submit_placeholder: 'https://youtube.com/watch?v=...',
    content_submit_button: 'Отправить на проверку',
    content_history_title: 'Ваши заявки',
    content_no_submissions: 'Вы еще не отправляли ни одного видео.',
    content_status_pending: 'Ожидает',
    content_status_approved: 'Одобрено',
    content_status_rejected: 'Отклонено',
    profile: 'Досье',
    sub_contacts: 'Контакты',
    sub_boosts: 'Усиления',
    sub_disguise: 'Маскировка',
    sub_market: 'Рынок',
    sub_cell: 'Ячейка',
    sub_content: 'Контент',
    completed: 'Выполнено',
    unlock_for: 'Открыть за',
    go_to_task: 'Перейти',
    claim: 'Забрать',
    enter_secret_code: 'Ввести код',
    claim_reward: 'Забрать награду',
    market_wallet_connected: 'Кошелек успешно подключен',
    wallet_disconnected: 'Кошелек отключен',
    connect_your_ton_wallet: 'Подключить TON кошелек',
    connect_wallet_task_desc: 'Для участия в аирдропе подключите свой TON кошелек.',
    missions: 'Директивы',
    sub_daily: 'Ежедневные',
    sub_airdrop: 'Airdrop',
    airdrop_description: 'Выполняйте специальные одноразовые задания, чтобы заработать большие награды для будущего аирдропа.',
    leaderboard: 'Таблица лидеров',
    your_league: 'Ваша лига',
    total_players: 'Всего агентов',
    won_item: 'Вы получили предмет',
    task_unlocked: 'Задание разблокировано',
    profit_boost: 'к прибыли',
    close: 'Закрыть',
    glitch_codes_title: 'Глитч-коды',
    glitch_codes_desc: 'Вводите найденные 4-значные коды, чтобы получить награды.',
    activate: 'Активировать',
    claimed: 'Получено',
    no_glitch_codes_found: 'Еще не найдено кодов.',
    penalty_title: 'Штраф',
    penalty_close: 'Понятно',
    exchange: 'Схрон',
    mine: 'Майнинг',
    boost_purchased: 'Буст приобретен!',
    upgrade_purchased: 'Улучшение приобретено!',
    task_completed: 'задание выполнено',
    combo_collected: 'Комбо собрано!',
    cipher_solved: 'Шифр разгадан!',
    glitch_code_claimed: 'Глитч-код активирован!',
    tooltip_energy: 'Это ваша Выносливость. Она тратится на тапы и восстанавливается со временем.',
    tooltip_suspicion: 'Это ваш уровень Подозрения. Высокорисковые действия повышают его. Если он заполнится, вас оштрафуют.',
    limit_reached: 'Лимит достигнут',
    limit_today: 'Лимит:',
    reset_limit_for: 'Сбросить за',
    lvl: 'Ур',
    create_cell: 'Создать ячейку',
    enter_cell_name: 'Введите название ячейки',
    create: 'Создать',
    join_cell: 'Присоединиться к ячейке',
    enter_invite_code: 'Введите код приглашения',
    join: 'Присоединиться',
    informant_dossier: 'Досье информатора',
    recruit_informant: 'Завербовать информатора',
    recruit_informant_desc: 'Завербуйте сгенерированного ИИ информатора, чтобы увеличить прибыль вашей ячейки.',
    recruiting: 'Вербовка...',
    recruit: 'Завербовать',
    cell: 'Ячейка',
    no_cell_info: 'Вы не являетесь частью ячейки. Создайте свою или присоединитесь по коду-приглашению.',
    total_cell_profit: 'Общая прибыль',
    members: 'Участники',
    cell_bank: 'Банк ячейки',
    cell_tickets: 'Билеты на битву',
    invite_code: 'Код приглашения',
    copy: 'Копировать',
    buy_ticket: 'Купить билет на битву',
    leave_cell: 'Покинуть ячейку',
    confirm_leave_cell: 'Вы уверены, что хотите покинуть ячейку?',
    cipher_hint: 'Введите код Морзе для сегодняшнего слова',
    cancel_morse_mode: 'Отменить',
    daily_cipher: 'Ежедневный шифр',
    mine_upgrades: 'Улучшения',
    combo_not_active: 'Комбо сегодня неактивно.',
    find_cards: 'Найдите и прокачайте эти карты сегодня, чтобы получить большой приз!',
    claimed_today: 'Получено',
    check: 'Проверить',
    suspicion: 'Подозрение',
  },
};
