

import React from 'react';
import { League, Upgrade, UpgradeCategory, Boost, DailyTask, LocalizedString, SpecialTask, BlackMarketCard, CoinSkin } from './types';

// --- ROLE MANAGEMENT ---
// The primary admin. Has all rights.
export const ADMIN_TELEGRAM_ID = '7327258482'; 
// Users who can access the admin panel but have slightly fewer rights than the main admin.
export const MODERATOR_TELEGRAM_IDS: string[] = ['987654321']; // Add moderator IDs here


// --- BOT CONFIGURATION ---
export const TELEGRAM_BOT_NAME = 'Ukhyliantbot';
// IMPORTANT: Replace 'app' with the "App Short Name" from BotFather for deep links to work
export const MINI_APP_NAME = 'ukhyliant_game';


// --- GAME CONFIGURATION ---
export const INITIAL_UPGRADES: Upgrade[] = [
    { id: 'doc1', name: { en: 'Student ID', ua: 'Студентський квиток', ru: 'Студенческий билет' }, price: 100, profitPerHour: 10, category: UpgradeCategory.Documents, iconUrl: 'https://api.iconify.design/twemoji/graduation-cap.svg', suspicionModifier: -5 },
    { id: 'doc2', name: { en: 'Disability Certificate', ua: 'Довідка про інвалідність', ru: 'Справка об инвалидности' }, price: 1500, profitPerHour: 80, category: UpgradeCategory.Documents, iconUrl: 'https://api.iconify.design/twemoji/wheelchair-symbol.svg', suspicionModifier: -10 },
    { id: 'doc3', name: { en: 'White Ticket', ua: 'Білий квиток', ru: 'Білий квиток' }, price: 10000, profitPerHour: 500, category: UpgradeCategory.Documents, iconUrl: 'https://api.iconify.design/twemoji/page-facing-up.svg', suspicionModifier: 5 },
    { id: 'leg1', name: { en: 'Lawyer Consultation', ua: 'Консультація адвоката', ru: 'Консультация адвоката' }, price: 500, profitPerHour: 25, category: UpgradeCategory.Legal, iconUrl: 'https://api.iconify.design/twemoji/balance-scale.svg', suspicionModifier: 0 },
    { id: 'leg2', name: { en: 'Open a Fake Company', ua: 'Відкрити фіктивну фірму', ru: 'Открыть фиктивную фирму' }, price: 5000, profitPerHour: 200, category: UpgradeCategory.Legal, iconUrl: 'https://api.iconify.design/twemoji/office-building.svg', suspicionModifier: 15 },
    { id: 'life1', name: { en: 'Hide in the Village', ua: 'Сховатись в селі', ru: 'Спрятаться в деревне' }, price: 2000, profitPerHour: 100, category: UpgradeCategory.Lifestyle, iconUrl: 'https://api.iconify.design/twemoji/hut.svg', suspicionModifier: -2 },
    { id: 'life2', name: { en: 'Rent a Bunker', ua: 'Орендувати бункер', ru: 'Арендовать бункер' }, price: 25000, profitPerHour: 1100, category: UpgradeCategory.Lifestyle, iconUrl: 'https://api.iconify.design/twemoji/locked.svg', suspicionModifier: 10 },
    { id: 'spec1', name: { en: 'Border Crossing', ua: 'Перетин кордону', ru: 'Пересечение границы' }, price: 100000, profitPerHour: 4000, category: UpgradeCategory.Special, iconUrl: 'https://api.iconify.design/twemoji/world-map.svg', suspicionModifier: 25 },
    { id: 'spec2', name: { en: 'New Identity', ua: 'Нова особистість', ru: 'Новая личность' }, price: 500000, profitPerHour: 20000, category: UpgradeCategory.Special, iconUrl: 'https://api.iconify.design/twemoji/performing-arts.svg', suspicionModifier: 50 },
];

export const INITIAL_TASKS: DailyTask[] = [
    { id: 'task1', name: { en: 'Tap 500 times', ua: 'Натисни 500 разів', ru: 'Нажми 500 раз' }, type: 'taps', reward: { type: 'coins', amount: 1000 }, requiredTaps: 500, suspicionModifier: 0 },
    { id: 'task2', name: { en: 'Daily Check-in', ua: 'Щоденний візит', ru: 'Ежедневный визит' }, type: 'taps', reward: { type: 'coins', amount: 500 }, requiredTaps: 1, suspicionModifier: -1 },
    { id: 'task3', name: { en: 'Join Telegram', ua: 'Підпишись на Telegram', ru: 'Подпишись на Telegram' }, type: 'telegram_join', reward: { type: 'profit', amount: 100 }, url: 'https://t.me/durov', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/82/Telegram_logo.svg', suspicionModifier: 0 }
];

export const INITIAL_SPECIAL_TASKS: SpecialTask[] = [
    { id: 'special1', name: { en: 'Join Our Channel', ua: 'Приєднайся до каналу', ru: 'Присоединись к каналу' }, description: { en: 'Get a huge bonus for joining our news channel!', ua: 'Отримай великий бонус за підписку на наш канал новин!', ru: 'Получи большой бонус за подписку на наш новостной канал!' }, type: 'telegram_join', url: 'https://t.me/durov', reward: { type: 'coins', amount: 100000 }, priceStars: 5, isOneTime: true, suspicionModifier: 0 },
    { id: 'special2', name: { en: 'Watch Review', ua: 'Подивись огляд', ru: 'Посмотри обзор' }, description: { en: 'Watch a video review and get rewarded.', ua: 'Подивись відео-огляд та отримай нагороду.', ru: 'Посмотри видео-обзор.'}, type: 'video_watch', url: 'https://youtube.com', reward: { type: 'coins', amount: 50000 }, priceStars: 0, isOneTime: true, suspicionModifier: 0 },
];

export const INITIAL_BOOSTS: Boost[] = [
    { id: 'boost_full_energy', name: { en: 'Full Energy', ua: 'Повна енергія', ru: 'Полная энергия' }, description: { en: 'Instantly refill your energy.', ua: 'Миттєво відновити енергію.', ru: 'Мгновенно восстановить энергию.' }, iconUrl: 'https://api.iconify.design/twemoji/high-voltage.svg', costCoins: 2000, suspicionModifier: 1 },
    { id: 'boost_turbo_mode', name: { en: 'Turbo Mode', ua: 'Турбо-режим', ru: 'Турбо-режим' }, description: { en: 'x5 coins per tap for 20 seconds!', ua: 'x5 монет за тап протягом 20 секунд!', ru: 'x5 монет за тап в течение 20 секунд!' }, iconUrl: 'https://api.iconify.design/twemoji/fire.svg', costCoins: 2000, suspicionModifier: 2 },
    { id: 'boost_tap_guru', name: { en: 'Guru Tapper', ua: 'Гуру Тапів', ru: 'Гуру Тапов' }, description: { en: '+50% to coins per tap (compounding).', ua: '+50% до монет за тап (складний відсоток).', ru: '+50% к монетам за тап (сложный процент).' }, iconUrl: 'https://api.iconify.design/ph/hand-tapping-fill.svg?color=white', costCoins: 1000, suspicionModifier: 1 },
    { id: 'boost_energy_limit', name: { en: 'Energy Limit', ua: 'Ліміт Енергії', ru: 'Лимит Энергии' }, description: { en: 'x2 to your max energy capacity.', ua: 'x2 до максимального запасу енергії.', ru: 'x2 к максимальному запасу энергии.' }, iconUrl: 'https://api.iconify.design/ph/battery-plus-vertical-fill.svg?color=white', costCoins: 1000, suspicionModifier: 1 },
    { id: 'boost_suspicion_limit', name: { en: 'Suspicion Limit', ua: 'Ліміт Підозри', ru: 'Лимит Подозрения' }, description: { en: '+10 to max suspicion capacity.', ua: '+10 до макс. запасу підозри.', ru: '+10 к макс. запасу подозрения.' }, iconUrl: 'https://api.iconify.design/ph/shield-warning-fill.svg?color=white', costCoins: 1000, suspicionModifier: 0 },
];

export const INITIAL_BLACK_MARKET_CARDS: BlackMarketCard[] = [
    { id: 'bm_card1', name: {en: 'Shadow Courier', ua: 'Тіньовий кур\'єр', ru: 'Теневой курьер'}, profitPerHour: 5000, iconUrl: 'https://api.iconify.design/twemoji/motor-scooter.svg', boxType: 'coin', chance: 50, price: 50000, suspicionModifier: 8 },
    { id: 'bm_card2', name: {en: 'Offshore Account', ua: 'Офшорний рахунок', ru: 'Офшорный счёт'}, profitPerHour: 25000, iconUrl: 'https://api.iconify.design/twemoji/bank.svg', boxType: 'star', chance: 20, price: 250000, suspicionModifier: 20 },
];

export const DEFAULT_COIN_SKIN_ID = 'default_coin';

export const INITIAL_COIN_SKINS: CoinSkin[] = [
    { id: DEFAULT_COIN_SKIN_ID, name: {en: 'Default Coin', ua: 'Стандартна Монета', ru: 'Стандартная Монета'}, profitBoostPercent: 0, iconUrl: '/assets/coin.svg', boxType: 'direct', chance: 100, suspicionModifier: 0 },
    { id: 'skin_btc', name: {en: 'BTC', ua: 'BTC', ru: 'BTC'}, profitBoostPercent: 1, iconUrl: 'https://api.iconify.design/twemoji/coin.svg', boxType: 'coin', chance: 10, suspicionModifier: 0 },
    { id: 'skin_diamond', name: {en: 'Diamond', ua: 'Діамант', ru: 'Бриллиант'}, profitBoostPercent: 5, iconUrl: 'https://api.iconify.design/twemoji/gem-stone.svg', boxType: 'star', chance: 5, suspicionModifier: 0 },
];


// --- GAME MECHANICS ---
export const INITIAL_MAX_ENERGY = 1000;
export const ENERGY_REGEN_RATE = 2; // per second
export const SAVE_DEBOUNCE_MS = 1000;
export const REFERRAL_BONUS = 50000; // Coins for each referral
export const REFERRAL_PROFIT_SHARE = 0.10; // 10%

export const BOOST_PURCHASE_LIMITS: Record<string, number> = {
  'boost_tap_guru': 10,
  'boost_energy_limit': 10,
  'boost_suspicion_limit': 10,
  'boost_full_energy': 3,
};


// --- TRANSLATIONS ---
type TranslationKey = 
  | 'exchange' | 'mine' | 'friends' | 'boosts' | 'tasks' | 'admin' | 'player' | 'league'
  | 'missions' | 'profile' | 'airdrop'
  | 'sub_daily' | 'sub_airdrop' | 'sub_contacts' | 'sub_boosts' | 'sub_disguise' | 'sub_market' | 'sub_cell'
  | 'profit_per_hour' | 'energy' | 'mine_upgrades' | 'lvl'
  | 'get' | 'level' | 'price' | 'profit' | 'category' | 'icon' | 'actions' | 'save'
  | 'add_new_upgrade' | 'edit_upgrades' | 'edit_tasks' | 'task_name' | 'reward_coins'
  | 'required_taps' | 'add_new_task' | 'edit_boosts' | 'boost_name' | 'description' | 'cost' | 'add_new_boost'
  | 'login_with_telegram' | 'login' | 'logout' | 'enter_telegram_id' | 'copy_referral_link' | 'copied'
  | 'claim_reward' | 'completed' | 'airdrop_tasks' | 'airdrop_description' | 'unlock_for' | 'go_to_task' | 'claim'
  | 'edit_special_tasks' | 'task_type' | 'url' | 'price_stars' | 'add_new_special_task' | 'translate'
  | 'telegram_join' | 'social_follow' | 'video_watch' | 'referral_bonus' | 'your_referrals' | 'invite_friends'
  // Daily Events
  | 'daily_combo' | 'daily_cipher' | 'find_cards' | 'cipher_hint' | 'claimed_today' | 'combo_not_active'
  | 'enter_morse_mode' | 'cancel_morse_mode' | 'enter_secret_code' | 'check' | 'leaderboard'
  | 'your_league' | 'total_players'
  // Notifications
  | 'task_completed' | 'combo_collected' | 'cipher_solved' | 'task_unlocked'
  // Boosts
  | 'guru_tapper' | 'energy_limit' | 'turbo_mode' | 'full_energy' | 'boost_purchased' | 'suspicion_limit'
  | 'limit_today' | 'limit_reached'
  // Market & Skins
  | 'market' | 'skins' | 'black_market' | 'black_market_desc' | 'open_for' | 'open'
  | 'lootbox_coin' | 'lootbox_star' | 'profit_from_referrals'
  | 'skins_gallery' | 'skins_gallery_desc' | 'select_skin' | 'selected' | 'profit_boost'
  | 'won_item' | 'close'
  // Suspicion & Cells
  | 'suspicion' | 'suspicion_modifier' | 'cell' | 'cell_info' | 'create_cell' | 'join_cell' | 'leave_cell' | 'no_cell_info'
  | 'cell_name' | 'enter_cell_name' | 'create' | 'enter_invite_code' | 'join' | 'members'
  | 'total_cell_profit' | 'invite_code' | 'copy' | 'confirm_leave_cell'
  | 'cell_bank' | 'cell_tickets' | 'buy_ticket'
  // Informants
  | 'recruit_informant' | 'informants' | 'no_informants_recruited' | 'informant_dossier' | 'recruit' | 'recruiting'
  // Big Brother
  | 'big_brother_is_watching' | 'penalty_title' | 'penalty_close'
  // Glitch Codes
  | 'glitch_codes_title' | 'glitch_codes_desc' | 'activate' | 'claimed' | 'no_glitch_codes_found' | 'glitch_code_claimed'
  | 'is_final_event' | 'final_video_url' | 'skip_video'
  // Cell Battles
  | 'cell_battle' | 'battle_inactive' | 'battle_time_left' | 'join_battle' | 'view_leaderboard'
  | 'battle_your_score' | 'battle_leaderboard_title' | 'rank' | 'score'
  | 'battle_boosts' | 'battle_boosts_desc' | 'battle_boost_activate'
  // Admin Panel
  | 'nav_cells' | 'nav_cell_analytics' | 'nav_cell_config'
  | 'kpi_total_cells' | 'kpi_battle_participants' | 'kpi_total_bank' | 'kpi_tickets_spent'
  | 'cell_leaderboard' | 'total_profit' | 'battle_history' | 'battle_date' | 'winner'
  | 'prize_pool' | 'cell_config' | 'cell_economy' | 'battle_rewards' | 'battle_management'
  | 'battle_schedule' | 'informant_bonus_percent' | 'bank_tax_percent'
  | 'first_place_reward' | 'second_place_reward' | 'third_place_reward' | 'participant_reward'
  | 'force_start_battle' | 'force_end_battle' | 'battle_status' | 'battle_status_active' | 'battle_status_inactive'
  | 'schedule_frequency' | 'freq_weekly' | 'freq_biweekly' | 'freq_monthly'
  | 'schedule_day' | 'day_sun' | 'day_mon' | 'day_tue' | 'day_wed' | 'day_thu' | 'day_fri' | 'day_sat'
  | 'schedule_time_utc' | 'schedule_duration_hours'
  // Tooltips
  | 'tooltip_energy' | 'tooltip_suspicion'
  // Generic
  | 'loading' | 'cancel'
  | 'why_not_state_language';


export const TRANSLATIONS: Record<string, Record<TranslationKey, string>> = {
  en: {
    exchange: 'Stockpile',
    mine: 'Mine',
    missions: 'Directives',
    airdrop: 'Airdrop',
    profile: 'Dossier',
    sub_daily: 'Daily',
    sub_airdrop: 'Airdrop',
    sub_contacts: 'Contacts',
    sub_boosts: 'Boosts',
    sub_disguise: 'Disguise',
    sub_market: 'Market',
    sub_cell: 'Cell',
    friends: 'Contacts',
    boosts: 'Boosts',
    tasks: 'Tasks',
    admin: 'Admin',
    player: 'Player',
    league: 'League',
    profit_per_hour: 'Profit per hour',
    energy: 'Stamina',
    mine_upgrades: 'Mine Upgrades',
    lvl: 'lvl',
    get: 'Get',
    level: 'Level',
    price: 'Price',
    profit: 'Profit',
    category: 'Category',
    icon: 'Icon',
    actions: 'Actions',
    save: 'Save',
    add_new_upgrade: 'Add New Upgrade',
    edit_upgrades: 'Edit Upgrades',
    edit_tasks: 'Edit Daily Tasks',
    task_name: 'Task Name',
    reward_coins: 'Reward Coins',
    required_taps: 'Required Taps',
    add_new_task: 'Add New Task',
    edit_boosts: 'Edit Boosts',
    boost_name: 'Boost Name',
    description: 'Description',
    cost: 'Cost',
    add_new_boost: 'Add New Boost',
    login_with_telegram: 'Login with Telegram',
    login: 'Login',
    logout: 'Logout',
    enter_telegram_id: 'Enter your Telegram ID to simulate login',
    copy_referral_link: 'Copy Referral Link',
    copied: 'Copied!',
    claim_reward: 'Claim Reward',
    completed: 'Completed',
    airdrop_tasks: 'Airdrop Tasks',
    airdrop_description: 'Complete tasks to get rewarded in a future airdrop!',
    unlock_for: 'Unlock for',
    go_to_task: 'Go to Task',
    claim: 'Claim',
    edit_special_tasks: 'Edit Special Tasks',
    task_type: 'Task Type',
    url: 'URL',
    price_stars: 'Price in Stars',
    add_new_special_task: 'Add New Special Task',
    translate: 'Translate',
    telegram_join: 'Join Telegram',
    social_follow: 'Follow Social Media',
    video_watch: 'Watch Video',
    referral_bonus: 'Bonus per contact',
    your_referrals: 'Your contacts',
    invite_friends: 'Invite a Contact',
    daily_combo: 'Daily Combo',
    daily_cipher: 'Daily Cipher',
    find_cards: 'Find and upgrade these cards!',
    cipher_hint: 'Tap the code: . is short, - is long',
    claimed_today: 'Claimed Today',
    combo_not_active: 'Combo is not active today.',
    enter_morse_mode: 'Enter Code',
    cancel_morse_mode: 'Cancel',
    enter_secret_code: 'Enter Secret Code',
    check: 'Check',
    leaderboard: 'Leaderboard',
    your_league: 'Your League',
    total_players: 'Total Players',
    task_completed: 'completed!',
    combo_collected: 'Combo collected!',
    cipher_solved: 'Cipher solved!',
    task_unlocked: 'Task Unlocked',
    guru_tapper: 'Guru Tapper',
    energy_limit: 'Energy Limit',
    turbo_mode: 'Turbo Mode',
    full_energy: 'Full Energy',
    suspicion_limit: 'Suspicion Limit',
    boost_purchased: 'Boost purchased!',
    limit_today: 'Limit today:',
    limit_reached: 'Limit reached',
    market: 'Market',
    skins: 'Skins',
    black_market: 'Black Market',
    black_market_desc: 'Spend resources to open containers with exclusive rewards!',
    open_for: 'Open for',
    open: 'Open',
    lootbox_coin: 'Coin Container',
    lootbox_star: 'Star Container',
    profit_from_referrals: 'Profit from contacts',
    skins_gallery: 'Skins Gallery',
    skins_gallery_desc: 'Select an unlocked skin to get a profit boost.',
    select_skin: 'Select',
    selected: 'Selected',
    profit_boost: 'Profit Boost',
    won_item: 'You won',
    close: 'Close',
    suspicion: 'Suspicion',
    suspicion_modifier: 'Suspicion',
    cell: 'Cell',
    cell_info: 'Your central hub for coordinated actions and shared risk.',
    create_cell: 'Create Cell',
    join_cell: 'Join Cell',
    leave_cell: 'Leave Cell',
    no_cell_info: 'You are not part of a cell. Create one to invite your contacts or join an existing one.',
    cell_name: 'Cell Name',
    enter_cell_name: 'Enter a name for your cell',
    create: 'Create',
    enter_invite_code: 'Enter Invite Code',
    join: 'Join',
    members: 'Members',
    total_cell_profit: 'Total Cell Profit',
    invite_code: 'Invite Code',
    copy: 'Copy',
    confirm_leave_cell: 'Are you sure you want to leave this cell?',
    cell_bank: 'Cell Bank',
    cell_tickets: 'Battle Tickets',
    buy_ticket: 'Buy Ticket',
    recruit_informant: 'Recruit Informant',
    informants: 'Informants',
    no_informants_recruited: 'No informants recruited yet.',
    informant_dossier: 'Informant Dossier',
    recruit: 'Recruit',
    recruiting: 'Recruiting...',
    big_brother_is_watching: 'Big Brother is watching you',
    penalty_title: 'Penalty',
    penalty_close: 'Acknowledge',
    glitch_codes_title: 'Glitch Codes',
    glitch_codes_desc: 'Enter discovered codes from the system to claim rewards.',
    activate: 'Activate',
    claimed: 'Claimed',
    no_glitch_codes_found: 'No glitch codes found yet. Keep searching.',
    glitch_code_claimed: 'Glitch code activated!',
    is_final_event: 'Is Final Event?',
    final_video_url: 'Final Video URL',
    skip_video: 'Skip',
    cell_battle: 'Cell Battle',
    battle_inactive: 'The battle is currently inactive. Check back soon!',
    battle_time_left: 'Time Left',
    join_battle: 'Join Battle (1 Ticket)',
    view_leaderboard: 'View Leaderboard',
    battle_your_score: 'Your Score',
    battle_leaderboard_title: 'Battle Leaderboard',
    rank: 'Rank',
    score: 'Score',
    battle_boosts: 'Battle Boosts',
    battle_boosts_desc: 'Coming soon! Use cell funds to get an edge.',
    battle_boost_activate: 'Activate',
    loading: 'Loading...',
    cancel: 'Cancel',
    nav_cells: 'Cells',
    nav_cell_analytics: 'Analytics',
    nav_cell_config: 'Configuration',
    kpi_total_cells: 'Total Cells',
    kpi_battle_participants: 'Battle Participants',
    kpi_total_bank: 'Total Bank',
    kpi_tickets_spent: 'Tickets Spent',
    cell_leaderboard: 'Cell Leaderboard',
    total_profit: 'Total Profit',
    battle_history: 'Battle History',
    battle_date: 'Date',
    winner: 'Winner',
    prize_pool: 'Prize Pool',
    cell_config: 'Cell Configuration',
    cell_economy: 'Cell Economy',
    battle_rewards: 'Battle Rewards',
    battle_management: 'Battle Management',
    battle_schedule: 'Battle Schedule',
    informant_bonus_percent: 'Informant Bonus (%)',
    bank_tax_percent: 'Bank Tax (%)',
    first_place_reward: '1st Place Reward',
    second_place_reward: '2nd Place Reward',
    third_place_reward: '3rd Place Reward',
    participant_reward: 'Participant Reward',
    force_start_battle: 'Force Start Battle',
    force_end_battle: 'Force End Battle',
    battle_status: 'Battle Status',
    battle_status_active: 'Active',
    battle_status_inactive: 'Inactive',
    schedule_frequency: 'Frequency',
    freq_weekly: 'Weekly',
    freq_biweekly: 'Bi-weekly',
    freq_monthly: 'Monthly',
    schedule_day: 'Day of Week',
    day_sun: 'Sunday',
    day_mon: 'Monday',
    day_tue: 'Tuesday',
    day_wed: 'Wednesday',
    day_thu: 'Thursday',
    day_fri: 'Friday',
    day_sat: 'Saturday',
    schedule_time_utc: 'Start Time (UTC)',
    schedule_duration_hours: 'Duration (Hours)',
    tooltip_energy: 'This is your tappable coin pool. Each tap spends coins from here.',
    tooltip_suspicion: 'This grows with illegal activities. If it fills up, your assets will be confiscated!',
    why_not_state_language: 'Is there a reason you are not using the state language? The system is watching.'
  },
  ua: {
    exchange: 'Схрон',
    mine: 'Майнінг',
    missions: 'Директиви',
    airdrop: 'Airdrop',
    profile: 'Досьє',
    sub_daily: 'Щоденні',
    sub_airdrop: 'Airdrop',
    sub_contacts: 'Контакти',
    sub_boosts: 'Посилення',
    sub_disguise: 'Маскування',
    sub_market: 'Ринок',
    sub_cell: 'Осередок',
    friends: 'Контакти',
    boosts: 'Бусти',
    tasks: 'Завдання',
    admin: 'Адмінка',
    player: 'Гравець',
    league: 'Ліга',
    profit_per_hour: 'Прибуток на годину',
    energy: 'Витривалість',
    mine_upgrades: 'Покращення',
    lvl: 'рів',
    get: 'Отримати',
    level: 'Рівень',
    price: 'Ціна',
    profit: 'Прибуток',
    category: 'Категорія',
    icon: 'Іконка',
    actions: 'Дії',
    save: 'Зберегти',
    add_new_upgrade: 'Додати нове покращення',
    edit_upgrades: 'Редагувати покращення',
    edit_tasks: 'Редагувати щоденні завдання',
    task_name: 'Назва завдання',
    reward_coins: 'Нагорода монетами',
    required_taps: 'Необхідно тапів',
    add_new_task: 'Додати нове завдання',
    edit_boosts: 'Редагувати бусти',
    boost_name: 'Назва буста',
    description: 'Опис',
    cost: 'Вартість',
    add_new_boost: 'Додати новий буст',
    login_with_telegram: 'Увійти через Telegram',
    login: 'Увійти',
    logout: 'Вийти',
    enter_telegram_id: 'Введіть ваш Telegram ID для симуляції входу',
    copy_referral_link: 'Копіювати реф. посилання',
    copied: 'Скопійовано!',
    claim_reward: 'Отримати нагороду',
    completed: 'Виконано',
    airdrop_tasks: 'Завдання Airdrop',
    airdrop_description: 'Виконуйте завдання та отримуйте нагороди у майбутньому ейрдропі!',
    unlock_for: 'Розблокувати за',
    go_to_task: 'Перейти до завдання',
    claim: 'Забрати',
    edit_special_tasks: 'Редагувати спец. завдання',
    task_type: 'Тип завдання',
    url: 'Посилання',
    price_stars: 'Ціна в зірках',
    add_new_special_task: 'Додати спец. завдання',
    translate: 'Перекласти',
    telegram_join: 'Підписка Telegram',
    social_follow: 'Підписка на соц. мережі',
    video_watch: 'Перегляд відео',
    referral_bonus: 'Бонус за контакт',
    your_referrals: 'Ваші контакти',
    invite_friends: 'Запросити контакт',
    daily_combo: 'Щоденне комбо',
    daily_cipher: 'Щоденний шифр',
    find_cards: 'Знайди та прокачай ці картки!',
    cipher_hint: 'Відстукай код: . короткий, - довгий',
    claimed_today: 'Сьогодні забрано',
    combo_not_active: 'Комбо сьогодні неактивне.',
    enter_morse_mode: 'Ввести код',
    cancel_morse_mode: 'Скасувати',
    enter_secret_code: 'Введіть секретний код',
    check: 'Перевірити',
    leaderboard: 'Таблиця лідерів',
    your_league: 'Ваша ліга',
    total_players: 'Всього гравців',
    task_completed: 'виконано!',
    combo_collected: 'Комбо зібрано!',
    cipher_solved: 'Шифр розгадано!',
    task_unlocked: 'Завдання розблоковано',
    guru_tapper: 'Гуру Тапів',
    energy_limit: 'Ліміт Енергії',
    turbo_mode: 'Турбо-режим',
    full_energy: 'Повна Енергія',
    suspicion_limit: 'Ліміт Підозри',
    boost_purchased: 'Буст придбано!',
    limit_today: 'Ліміт сьогодні:',
    limit_reached: 'Ліміт вичерпано',
    market: 'Ринок',
    skins: 'Скіни',
    black_market: 'Чорний ринок',
    black_market_desc: 'Витрачайте ресурси, щоб відкривати контейнери з ексклюзивними нагородами!',
    open_for: 'Відкрити за',
    open: 'Відкрити',
    lootbox_coin: 'Контейнер за монети',
    lootbox_star: 'Контейнер за зірки',
    profit_from_referrals: 'Прибуток від контактів',
    skins_gallery: 'Галерея Скінів',
    skins_gallery_desc: 'Виберіть розблокований скін, щоб отримати бонус до прибутку.',
    select_skin: 'Обрати',
    selected: 'Обрано',
    profit_boost: 'Бонус до прибутку',
    won_item: 'Ви виграли',
    close: 'Закрити',
    suspicion: 'Підозра',
    suspicion_modifier: 'Підозра',
    cell: 'Осередок',
    cell_info: 'Ваш центр для координованих дій та спільних ризиків.',
    create_cell: 'Створити осередок',
    join_cell: 'Приєднатися',
    leave_cell: 'Покинути осередок',
    no_cell_info: 'Ви не є частиною осередку. Створіть свій, щоб запросити контактів, або приєднайтеся до існуючого.',
    cell_name: 'Назва осередку',
    enter_cell_name: 'Введіть назву для вашого осередку',
    create: 'Створити',
    enter_invite_code: 'Введіть код-запрошення',
    join: 'Приєднатися',
    members: 'Учасники',
    total_cell_profit: 'Загальний прибуток осередку',
    invite_code: 'Код-запрошення',
    copy: 'Копіювати',
    confirm_leave_cell: 'Ви впевнені, що хочете покинути цей осередок?',
    cell_bank: 'Банк осередку',
    cell_tickets: 'Квитки на битву',
    buy_ticket: 'Купити квиток',
    recruit_informant: 'Завербувати інформатора',
    informants: 'Інформатори',
    no_informants_recruited: 'Ще не завербовано жодного інформатора.',
    informant_dossier: 'Досьє інформатора',
    recruit: 'Завербувати',
    recruiting: 'Вербування...',
    big_brother_is_watching: 'Великий брат стежить за тобою',
    penalty_title: 'Покарання',
    penalty_close: 'Зрозуміло',
    glitch_codes_title: 'Глітч-коди',
    glitch_codes_desc: 'Вводьте знайдені в системі коди, щоб отримати нагороди.',
    activate: 'Активувати',
    claimed: 'Отримано',
    no_glitch_codes_found: 'Глітч-коди ще не знайдено. Продовжуйте пошук.',
    glitch_code_claimed: 'Глітч-код активовано!',
    is_final_event: 'Це фінальна подія?',
    final_video_url: 'URL фінального відео',
    skip_video: 'Пропустити',
    cell_battle: 'Битва осередків',
    battle_inactive: 'Битва наразі неактивна. Завітайте пізніше!',
    battle_time_left: 'Залишилось часу',
    join_battle: 'Вступити в бій (1 квиток)',
    view_leaderboard: 'Переглянути лідерів',
    battle_your_score: 'Ваш рахунок',
    battle_leaderboard_title: 'Таблиця лідерів битви',
    rank: 'Ранг',
    score: 'Рахунок',
    battle_boosts: 'Бойові бусти',
    battle_boosts_desc: 'Незабаром! Використовуйте кошти осередку для переваги.',
    battle_boost_activate: 'Активувати',
    loading: 'Завантаження...',
    cancel: 'Скасувати',
    nav_cells: 'Осередки',
    nav_cell_analytics: 'Аналітика',
    nav_cell_config: 'Конфігурація',
    kpi_total_cells: 'Всього осередків',
    kpi_battle_participants: 'Учасники битви',
    kpi_total_bank: 'Загальний банк',
    kpi_tickets_spent: 'Витрачено квитків',
    cell_leaderboard: 'Лідерборд осередків',
    total_profit: 'Загальний прибуток',
    battle_history: 'Історія битв',
    battle_date: 'Дата',
    winner: 'Переможець',
    prize_pool: 'Призовий фонд',
    cell_config: 'Конфігурація осередків',
    cell_economy: 'Економіка осередків',
    battle_rewards: 'Нагороди за битву',
    battle_management: 'Керування битвами',
    battle_schedule: 'Розклад битв',
    informant_bonus_percent: 'Бонус інформатора (%)',
    bank_tax_percent: 'Податок у банк (%)',
    first_place_reward: 'Нагорода за 1 місце',
    second_place_reward: 'Нагорода за 2 місце',
    third_place_reward: 'Нагорода за 3 місце',
    participant_reward: 'Нагорода учаснику',
    force_start_battle: 'Примусово почати битву',
    force_end_battle: 'Примусово завершити битву',
    battle_status: 'Статус битви',
    battle_status_active: 'Активна',
    battle_status_inactive: 'Неактивна',
    schedule_frequency: 'Частота',
    freq_weekly: 'Щотижня',
    freq_biweekly: 'Раз на два тижні',
    freq_monthly: 'Щомісяця',
    schedule_day: 'День тижня',
    day_sun: 'Неділя',
    day_mon: 'Понеділок',
    day_tue: 'Вівторок',
    day_wed: 'Середа',
    day_thu: 'Четвер',
    day_fri: 'П\'ятниця',
    day_sat: 'Субота',
    schedule_time_utc: 'Час початку (UTC)',
    schedule_duration_hours: 'Тривалість (години)',
    tooltip_energy: 'Це ваш запас монет для тапів. Кожен тап витрачає монети звідси.',
    tooltip_suspicion: 'Рівень підозри зростає від незаконних дій. Якщо він заповниться, ваші активи конфіскують!',
    why_not_state_language: 'Чому не державною? Система все бачить.'
  },
  ru: {
    exchange: 'Схрон',
    mine: 'Майнинг',
    missions: 'Директивы',
    airdrop: 'Airdrop',
    profile: 'Досье',
    sub_daily: 'Ежедневные',
    sub_airdrop: 'Airdrop',
    sub_contacts: 'Контакты',
    sub_boosts: 'Усиления',
    sub_disguise: 'Маскировка',
    sub_market: 'Рынок',
    sub_cell: 'Ячейка',
    friends: 'Контакты',
    boosts: 'Бусты',
    tasks: 'Задания',
    admin: 'Админка',
    player: 'Игрок',
    league: 'Лига',
    profit_per_hour: 'Прибыль в час',
    energy: 'Выносливость',
    mine_upgrades: 'Улучшения',
    lvl: 'ур',
    get: 'Получить',
    level: 'Уровень',
    price: 'Цена',
    profit: 'Прибыль',
    category: 'Категория',
    icon: 'Иконка',
    actions: 'Действия',
    save: 'Сохранить',
    add_new_upgrade: 'Добавить новое улучшение',
    edit_upgrades: 'Редактировать улучшения',
    edit_tasks: 'Редактировать ежедневные задания',
    task_name: 'Название задания',
    reward_coins: 'Награда монетами',
    required_taps: 'Необходимо тапов',
    add_new_task: 'Добавить новое задание',
    edit_boosts: 'Редактировать бусты',
    boost_name: 'Название буста',
    description: 'Описание',
    cost: 'Стоимость',
    add_new_boost: 'Добавить новый буст',
    login_with_telegram: 'Войти через Telegram',
    login: 'Войти',
    logout: 'Выйти',
    enter_telegram_id: 'Введите ваш Telegram ID для симуляции входа',
    copy_referral_link: 'Копировать реф. ссылку',
    copied: 'Скопировано!',
    claim_reward: 'Получить награду',
    completed: 'Выполнено',
    airdrop_tasks: 'Задания Airdrop',
    airdrop_description: 'Выполняйте задания и получайте награды в будущем эйрдропе!',
    unlock_for: 'Разблокировать за',
    go_to_task: 'Перейти к заданию',
    claim: 'Забрать',
    edit_special_tasks: 'Редактировать спец. задания',
    task_type: 'Тип задания',
    url: 'Ссылка',
    price_stars: 'Цена в звёздах',
    add_new_special_task: 'Добавить спец. задание',
    translate: 'Перевести',
    telegram_join: 'Подписка Telegram',
    social_follow: 'Подписка на соц. сети',
    video_watch: 'Просмотр видео',
    referral_bonus: 'Бонус за контакт',
    your_referrals: 'Ваши контакты',
    invite_friends: 'Пригласить контакт',
    daily_combo: 'Ежедневное комбо',
    daily_cipher: 'Ежедневный Шифр',
    find_cards: 'Найди и прокачай эти карты!',
    cipher_hint: 'Отстучи код: . короткий, - длинный',
    claimed_today: 'Сегодня забрано',
    combo_not_active: 'Комбо сегодня неактивно.',
    enter_morse_mode: 'Ввести код',
    cancel_morse_mode: 'Отмена',
    enter_secret_code: 'Введите секретный код',
    check: 'Проверить',
    leaderboard: 'Таблица лидеров',
    your_league: 'Ваша лига',
    total_players: 'Всего игроков',
    task_completed: 'выполнено!',
    combo_collected: 'Комбо собрано!',
    cipher_solved: 'Шифр разгадан!',
    task_unlocked: 'Задание разблокировано',
    guru_tapper: 'Гуру Тапов',
    energy_limit: 'Лимит Энергии',
    turbo_mode: 'Турбо-режим',
    full_energy: 'Полная Энергия',
    suspicion_limit: 'Лимит Подозрения',
    boost_purchased: 'Буст приобретён!',
    limit_today: 'Лимит сегодня:',
    limit_reached: 'Лимит исчерпан',
    market: 'Рынок',
    skins: 'Скины',
    black_market: 'Черный рынок',
    black_market_desc: 'Тратьте ресурсы, чтобы открывать контейнеры с эксклюзивными наградами!',
    open_for: 'Открыть за',
    open: 'Открыть',
    lootbox_coin: 'Контейнер за монеты',
    lootbox_star: 'Контейнер за звёзды',
    profit_from_referrals: 'Прибыль от контактов',
    skins_gallery: 'Галерея Скинов',
    skins_gallery_desc: 'Выберите разблокированный скин, чтобы получить бонус к прибыли.',
    select_skin: 'Выбрать',
    selected: 'Выбрано',
    profit_boost: 'Бонус к прибыли',
    won_item: 'Вы выиграли',
    close: 'Закрыть',
    suspicion: 'Подозрение',
    suspicion_modifier: 'Подозрение',
    cell: 'Ячейка',
    cell_info: 'Ваш центр для координированных действий и общих рисков.',
    create_cell: 'Создать ячейку',
    join_cell: 'Присоединиться',
    leave_cell: 'Покинуть ячейку',
    no_cell_info: 'Вы не состоите в ячейке. Создайте свою, чтобы пригласить контактов, или присоединитесь к существующей.',
    cell_name: 'Название ячейки',
    enter_cell_name: 'Введите название для вашей ячейки',
    create: 'Создать',
    enter_invite_code: 'Введите код-приглашение',
    join: 'Присоединиться',
    members: 'Участники',
    total_cell_profit: 'Общая прибыль ячейки',
    invite_code: 'Код-приглашение',
    copy: 'Копировать',
    confirm_leave_cell: 'Вы уверены, что хотите покинуть эту ячейку?',
    cell_bank: 'Банк ячейки',
    cell_tickets: 'Билеты на битву',
    buy_ticket: 'Купить билет',
    recruit_informant: 'Завербовать информатора',
    informants: 'Информаторы',
    no_informants_recruited: 'Ещё не завербовано ни одного информатора.',
    informant_dossier: 'Досье информатора',
    recruit: 'Завербовать',
    recruiting: 'Вербовка...',
    big_brother_is_watching: 'Большой брат следит за тобой',
    penalty_title: 'Наказание',
    penalty_close: 'Принять',
    glitch_codes_title: 'Глитч-коды',
    glitch_codes_desc: 'Вводите найденные в системе коды, чтобы получить награды.',
    activate: 'Активировать',
    claimed: 'Получено',
    no_glitch_codes_found: 'Глитч-коды еще не найдены. Продолжайте поиск.',
    glitch_code_claimed: 'Глитч-код активирован!',
    is_final_event: 'Это финальное событие?',
    final_video_url: 'URL финального видео',
    skip_video: 'Пропустить',
    cell_battle: 'Битва ячеек',
    battle_inactive: 'Битва в данный момент неактивна. Загляните позже!',
    battle_time_left: 'Осталось времени',
    join_battle: 'Вступить в бой (1 билет)',
    view_leaderboard: 'Посмотреть лидеров',
    battle_your_score: 'Ваш счёт',
    battle_leaderboard_title: 'Таблица лидеров битвы',
    rank: 'Ранг',
    score: 'Счёт',
    battle_boosts: 'Боевые бусты',
    battle_boosts_desc: 'Скоро! Используйте средства ячейки для получения преимущества.',
    battle_boost_activate: 'Активировать',
    loading: 'Загрузка...',
    cancel: 'Отмена',
    nav_cells: 'Ячейки',
    nav_cell_analytics: 'Аналитика',
    nav_cell_config: 'Конфигурация',
    kpi_total_cells: 'Всего ячеек',
    kpi_battle_participants: 'Участники битвы',
    kpi_total_bank: 'Общий банк',
    kpi_tickets_spent: 'Потрачено билетов',
    cell_leaderboard: 'Лидерборд ячеек',
    total_profit: 'Общая прибыль',
    battle_history: 'История битв',
    battle_date: 'Дата',
    winner: 'Победитель',
    prize_pool: 'Призовой фонд',
    cell_config: 'Конфигурация ячеек',
    cell_economy: 'Экономика ячеек',
    battle_rewards: 'Награды за битву',
    battle_management: 'Управление битвами',
    battle_schedule: 'Расписание битв',
    informant_bonus_percent: 'Бонус информатора (%)',
    bank_tax_percent: 'Налог в банк (%)',
    first_place_reward: 'Награда за 1 место',
    second_place_reward: 'Награда за 2 место',
    third_place_reward: 'Награда за 3 место',
    participant_reward: 'Награда участнику',
    force_start_battle: 'Принудительно начать битву',
    force_end_battle: 'Принудительно завершить битву',
    battle_status: 'Статус битвы',
    battle_status_active: 'Активна',
    battle_status_inactive: 'Неактивна',
    schedule_frequency: 'Частота',
    freq_weekly: 'Еженедельно',
    freq_biweekly: 'Раз в две недели',
    freq_monthly: 'Ежемесячно',
    schedule_day: 'День недели',
    day_sun: 'Воскресенье',
    day_mon: 'Понедельник',
    day_tue: 'Вторник',
    day_wed: 'Среда',
    day_thu: 'Четверг',
    day_fri: 'Пятница',
    day_sat: 'Суббота',
    schedule_time_utc: 'Время начала (UTC)',
    schedule_duration_hours: 'Длительность (часы)',
    tooltip_energy: 'Это ваш запас монет для тапов. Каждый тап тратит монеты отсюда.',
    tooltip_suspicion: 'Уровень подозрения растет от незаконных действий. Если он заполнится, ваши активы конфискуют!',
    why_not_state_language: 'Почему не на государственном языке? Система всё видит.'
  },
};